config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :log_entries, only: %i[show edit update destroy]

  resources :vehicles do
    resources :log_entries, only: %i[index create new]
  end

  resources :authentication, only: [] do
    collection do
      get :login, to: 'authentication#show'
      post :login
      get :logout
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'vehicles#index'
end

app/models/log_entry.rb
# frozen_string_literal: true

class LogEntry < ApplicationRecord
  belongs_to :vehicle

  validates :title, :cost_cents, :performed_on, :recorded_mileage, presence: true
  validates :performed_on, comparison: { less_than_or_equal_to: -> { Date.current } }
  validates :cost_cents, numericality: { greater_than_or_equal_to: 0 }
  validates :recorded_mileage, numericality: { greater_than_or_equal_to: 0 }

  monetize :cost_cents, allow_nil: false

  def formatted_mileage
    recorded_mileage.to_fs(:delimited)
  end
end

app/controllers/log_entries_controller.rb
# frozen_string_literal: true

class LogEntriesController < ApplicationController
  before_action :set_vehicle, only: %i[index create new]
  before_action :set_log_entry, only: %i[show edit update destroy]
  authorize_resource

  def index
    @log_entries = vehicle.log_entries

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  # GET /log_entries/1 or /log_entries/1.json
  def show; end

  # GET /log_entries/new
  def new
    @log_entry = vehicle.log_entries.new
  end

  # GET /log_entries/1/edit
  def edit; end

  # POST /log_entries or /log_entries.json
  def create
    @log_entry = vehicle.log_entries.new(log_entry_params)

    respond_to do |format|
      if @log_entry.save
        format.html { redirect_to log_entry_url(@log_entry), notice: I18n.t('log_entry.create.success') }
        format.json { render :show, status: :created, location: @log_entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @log_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /log_entries/1 or /log_entries/1.json
  def update
    respond_to do |format|
      if @log_entry.update(log_entry_params)
        format.html { redirect_to log_entry_url(@log_entry), notice: I18n.t('log_entry.update.success') }
        format.json { render :show, status: :ok, location: @log_entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @log_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /log_entries/1 or /log_entries/1.json
  def destroy
    @log_entry.destroy!

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to vehicle_path(@log_entry.vehicle), notice: I18n.t('log_entry.destroy.success') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_log_entry
    @log_entry = LogEntry.find(params[:id])
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:vehicle_id])
  end

  # Only allow a list of trusted parameters through.
  def log_entry_params
    params
      .require(:log_entry)
      .permit(:title,
              :description,
              :cost,
              :recorded_mileage,
              :performed_on,
              :has_paper_record)
  end

  attr_accessor :vehicle
end

app/helpers/log_entries_helper.rb
# frozen_string_literal: true

module LogEntriesHelper
end

app/views/log_entries/_form.html.erb
<%= form_with(model: [ @vehicle, @log_entry ], class: "contents") do |form| %>
  <% if @log_entry.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@log_entry.errors.count, "error") %> prohibited this log_entry from being saved:</h2>

      <ul>
        <% @log_entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/log_entries/_log_entry.html.erb
<div id="<%= dom_id log_entry %>">
  <% if action_name != "show" %>
    <%= link_to "Show this log entry", log_entry, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this log entry", edit_log_entry_path(log_entry), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/log_entries/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing log entry</h1>

  <%= render "form", log_entry: @log_entry %>

  <%= link_to "Show this log entry", @log_entry, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/log_entries/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Log entries</h1>
    <%= link_to "New log entry", new_vehicle_log_entry_path(@vehicle), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="log_entries" class="min-w-full">
    <%= render @log_entries %>
  </div>
</div>

app/views/log_entries/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New log entry</h1>

  <%= render "form", log_entry: @log_entry, vehicle: @vehicle%>
</div>

app/views/log_entries/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @log_entry %>

    <%= link_to "Edit this log_entry", edit_log_entry_path(@log_entry), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this log_entry", log_entry_path(@log_entry), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>