config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :log_entries, only: %i[show edit update destroy]

  resources :vehicles do
    resources :log_entries, only: %i[index create new]
  end

  resources :authentication, only: [] do
    collection do
      get :login, to: 'authentication#show'
      post :login
      get :logout
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'vehicles#index'
end

app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  STARTING_YEAR = 1925

  validates :vin, uniqueness: true
  validates :vin, :make, :model, :year, presence: true
  validates :year, numericality: { only_integer: true }

  validate :model_year_is_valid

  has_many :log_entries, dependent: :destroy

  def friendly_title
    "#{year} #{make} #{model}"
  end

  private

  def model_year_is_valid
    latest_possible_model_year = Date.current.year + 1
    return if year.in? STARTING_YEAR..latest_possible_model_year

    errors.add(
      :year,
      "outside valid range (cannot be less than #{STARTING_YEAR} or greater than #{latest_possible_model_year})"
    )
  end
end

app/controllers/vehicles_controller.rb
# frozen_string_literal: true

class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[show edit update destroy]
  authorize_resource

  # GET /vehicles or /vehicles.json
  def index
    @vehicles = Vehicle.all

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit; end

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicle_url(@vehicle), notice: I18n.t('vehicle.create.success') }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_url(@vehicle), notice: I18n.t('vehicle.update.success') }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy!

    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: I18n.t('vehicle.destroy.success') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def vehicle_params
    params.require(:vehicle).permit(:vin, :make, :model, :year)
  end
end

app/helpers/vehicles_helper.rb
# frozen_string_literal: true

module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, class: "contents") do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/vehicles/_vehicle.html.erb
<div id="<%= dom_id vehicle %>">
  <h2 class="font-bold text-3xl"><%= vehicle.friendly_title %></h2>
</div>

app/views/vehicles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing Vehicle</h1>

  <%= render "form", vehicle: @vehicle %>

  <%= link_to "Show this vehicle", @vehicle, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to vehicles", vehicles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/vehicles/index.html.erb
<div class="h-full w-full mx-4">
  <% if notice.present? %>
    <p id="notice" class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block">
    <%= notice %>
    </p>
  <% end %>

  <div class="flex justify-between items-center text-slate-700">
    <h1 class="font-bold text-4xl">Vehicles</h1>
    <%= render LinkButtonComponent.new(text: "Add Vehicle", href: new_vehicle_path) %>
  </div>

  <% if @vehicles.count.zero? %>
    <div class="h-2/5 flex justify-center align-middle">
    <span class="m-auto text-slate-400 font-semibold">
      <p>No vehicles saved yet.</p>
      <p>Add one <%= link_to "here", new_vehicle_path, class: "underline" %>.</p>
    </span>
    </div>
  <% else %>
    <div id="vehicles" class="w-full mt-10">
      <%= render VehicleListComponent.new(@vehicles) %>
    </div>
  <% end %>
</div>

app/views/vehicles/new.html.erb
<div class="h-full w-full mx-4 md:w-3/5 md:mx-auto">
  <span class="flex flex-row justify-between mb-4">
    <%= render BackLinkComponent.new("All vehicles", vehicles_path) %>
  </span>
  <span>
    <h1 class="font-bold text-4xl text-slate-700">New Vehicle</h1>
  </span>

  <%= render "form", vehicle: @vehicle %>
</div>

app/views/vehicles/show.html.erb
<div class="w-full">
  <div class="mx-auto w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render VehicleViewComponent.new(@vehicle) %>
  </div>
</div>